### ISSUE TITLE
Request: I need reports on the functionality of this driver

### ISSUE THREAD

**Issue by morrownr** [morrownr/8821au#1]
Under Tested Hardware in the README, it says "Pending". The reason is that I have not been able to test this driver myself due to my adapter being delayed.

I have worked hard on this driver and it compiles on the supported platforms but I do not know if it actually works. Please take the time to write me a note.

I should have an adapter soon.

Regards.

**Comment by morrownr** [comment]
I have an adapter now. Testing with it showed a problem with kernel 5.8 support so I had to work that issue. I think that issue is under control so I'm pretty sure things are good to go all the way through kernel 5.10. My testing with kernel 5.10 is problematic due to various issues with various distros and k5.10 but that will get worked out given time.

If anyone is using kernel 5.8 or higher, I would appreciate a report. Thanks.

**Comment by kimocoder** [comment]
@morrownr where did you get this source?

**Comment by morrownr** [comment]
Edimax support website:

https://www.edimax.com/edimax/download/download/data/edimax/global/download/
