### ISSUE TITLE
Need testers for New Version v5.12.5.2  (20210708)

### ISSUE THREAD

**Issue by morrownr** [morrownr/8821au#18]
@MSLaaf @5kft 

All,

I have a new version of this driver nearly ready for release and I would like for a few folks to test it as soon as I make the repo public so as to catch any major issues and make suggestions. Let me know if you are interested.

The new driver is based on source from Realtek that is dated 2021-07-06 so it is very recent. Supposedly it supports WPA3. It is a clean compile. It, of course, came with no documentation whatsoever.

Nick

**Comment by 5kft** [comment]
@morrownr Happy to give this a try on both arm64 and amd64.  I may not try WPA3 until the weekend, however...!

**Comment by morrownr** [comment]
@5kft 

That is great!  I have made the new repo public:

https://github.com/morrownr/8821au-20210708

The old repo (here) will stay until it needs to go away. Notice that the new repo uses the date of the code release in the name to differentiate it from this repo.

Notes: There is a lot of new code from Realtek in this version. My testing so far seems to indicate good performance in both managed and master modes. Please test test test. No detail is too small. Let me know what your results are as you have time.

Nick
