### ISSUE TITLE
RTL8811AU No MAC address on USB device insert/add?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [morrownr/8821au#21]
Installed driver, have done this many times on various systems, x86 as well as Pi devices, etc.  But came across the odd behavior, on an older PC, i386 (i686), when installing wifi dongle, it is seen as USB device, but no MAC address assigned?

[  657.065852] usb 2-2: USB disconnect, device number 2
[  660.921658] usb 2-1: new full-speed USB device number 3 using uhci_hcd
[  661.117597] usb 2-1: New USB device found, idVendor=0bda, idProduct=a811, bcdDevice= 2.00
[  661.117722] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  661.117800] usb 2-1: Product: 802.11ac WLAN Adapter
[  661.117858] usb 2-1: Manufacturer: Realtek
[  661.117907] usb 2-1: SerialNumber: 00e04c000001

tried switching from ehci to uhci, no joy.  This first time I have seen this, usually at least I MAC address is assigned, and then it is just a matter of getting the right firmware or driver installed.

\# uname -mr; mokutil --sb-state; lsusb; rfkill list all; dkms status; iw dev; iw reg get
5.10.0-18-686-pae i686
EFI variables are not supported on this system
Bus 003 Device 002: ID 0624:0201 Avocent Corp. Virtual Media KVM Module
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 003: ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
8188eu, 5.3.9, 5.10.0-18-686-pae, i686: installed
rtl8812au, 5.13.6, 5.10.0-18-686-pae, i686: installed
global
country 00: DFS-UNSET
        (755 - 928 @ 2), (N/A, 20), (N/A), PASSIVE-SCAN
        (2402 - 2472 @ 40), (N/A, 20), (N/A)
        (2457 - 2482 @ 20), (N/A, 20), (N/A), AUTO-BW, PASSIVE-SCAN
        (2474 - 2494 @ 20), (N/A, 20), (N/A), NO-OFDM, PASSIVE-SCAN
        (5170 - 5250 @ 80), (N/A, 20), (N/A), AUTO-BW, PASSIVE-SCAN
        (5250 - 5330 @ 80), (N/A, 20), (0 ms), DFS, AUTO-BW, PASSIVE-SCAN
        (5490 - 5730 @ 160), (N/A, 20), (0 ms), DFS, PASSIVE-SCAN
        (5735 - 5835 @ 80), (N/A, 20), (N/A), PASSIVE-SCAN
        (57240 - 63720 @ 2160), (N/A, 0), (N/A)

On the same system I was able to get various other wifi dongles to work, RTL8188CUS, RTL8188EUS for example.  The only issue with these was they only got ipv6 addresses (local mode) not ipv4 or ipv6 via DHCP until I forced the association wpa_supplicant, and did an explict DHCP request, via dhcpcd.  See this before sometimes at well but easy to deal with, since the firmware/drivers actually work, and the device is 'seen', and MAC address is assigned/established.

Also, I have 3 of these RTL8811AU dongles that all work on Pi OS 11, with the correct firmware/driver, so the dongles are functional hardware.

Thought you might have a suggestion on what to try next?

**Comment by morrownr** [comment]
Hi @Jibun-no-Kage 

> ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter

This tells me your adapters is using a 8811au chipset.

> rtl8812au, 5.13.6, 5.10.0-18-686-pae, i686: installed

This tells me you have installed the driver for the 8812au chipset.

I don't see where you have installed the 8821au driver, which is the correct one for the 8811au chipset:

Here is the Main Menu for the site:

https://github.com/morrownr/USB-WiFi

Menu item 5 will give you a document that gives links to the Realtek drivers that are maintained here. 

You should probably remove the rtl8812au driver unless your have a 8812au based adapter and then install the 8821au driver per installation guidance. If you have any problems, please start a new issue in the `8821au-20210708` repo.

Regards,

Nick

**Comment by Jibun-no-Kage** [comment]
I must be getting old... what a typo., "12" versus "21".

**Comment by morrownr** [comment]
It happens.
