### ISSUE TITLE
Issues after updating to 6.4 Kernel/ Fedora

### ISSUE THREAD

**Issue by basushaunak** [morrownr/8821au#23]
My Fedora 38 recently got updated to 6.4 kernel and the device stopped work. So as per instructions I uninstalled the driver using remove-driver.sh.
But even after it informed that it has successfully removed the driver, when reinstalling after reboot, I am getting this error:
Checking for previously installed drivers.
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/rtl8821au/5.12.5.2/source/dkms.conf does not exist.
: ---------------------------

Starting installation.
Installing 8821au.conf to /etc/modprobe.d
The dkms installation routines are in use.
Copying source files to /usr/src/rtl8821au-5.12.5.2
Error! DKMS tree already contains: rtl8821au-5.12.5.2
You cannot add the same module/version combo more than once.
This driver may already be installed.
Run the following and then reattempt installation.
$ sudo ./remove-driver.sh

Any tips/ suggestions ?
Thanks

**Comment by morrownr** [comment]
Hi @basushaunak 

That should have worked but bugs happen.

Post the result of 

$ sudo dkms status

Run the following line and then try $ sudo sh install-driver.sh

$ sudo dkms remove -m rtl8821au -v 5.12.5.2 --all

**Comment by morrownr** [comment]
Glad you solved the issue. It is not clear to me how my script could have failed to clean already installed driver out so I will investigate as I have time.
