### ISSUE TITLE
MAC Randomized?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [morrownr/8821au#24]
Bus 001 Device 002: ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter

Drivers installed...

Even with explicit MAC randomization disabled...
\# ls
8812au-20210629  8821au-20210708  8821cu-20210916

\# nano /etc/NetworkManager/conf.d/disable-randomization.conf
[device]
wifi.scan-rand-mac-address=no

[connection]
wifi.cloned-mac-address=no

Each reboot get randomized MAC.  Is there not a rtw... setting to disable this?  Or is something above out of wack?

**Comment by morrownr** [comment]
What distro and what are you doing?

**Comment by Jibun-no-Kage** [comment]
Debian 12

**Comment by morrownr** [comment]
Nothing pops to mind. I've read the history on this MAC randomization subject before but don't remember much. You might think about making a post in a Debian forum.

Speaking of Debian 12. I am currently testing it on a spare system to see if it would be a good distro for my core dev system. I think Debian is finally to the point that it may work.

**Comment by Jibun-no-Kage** [comment]
Cool.... I am running a couple of VMs on the Droid, to float my database, DNS, DHCP, MQTT services.  Could have used docker, but everything in one VM works, less complex networking.  The Droid is a processing beast, with 16GB RAM and the overkill processor for a SBC.

What is odd about the MAC randomization it is ONLY happening on one specific dongle... given the specific chip.  Found a reference saying that the MAC can be randomized by the driver... if the driver has trouble reading the burned in MAC or via the firmware?  Does that by any change ring a bell?

**Comment by Jibun-no-Kage** [comment]
Oh... A work-around is forcing NetworkManager to use the, what I believe, is the burned in MAC, via the /etc/NetworkManager/NetworkManager.conf file:

[connection]
wifi.cloned-mac-address=XX:XX:XX:XX:XX:XX

Only happens with the following dongle:

\# lsusb
Bus 001 Device 004: ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter

**Comment by morrownr** [comment]
At least you found a work-around. It could be something in this driver but having the time to chase the problem down is an issue with me.

**Comment by Jibun-no-Kage** [comment]
If you happen to find out why, would be nice to know of course.  But understand.
